DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`
(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  salt VARCHAR(50) NOT NULL,
  createTime DATETIME NOT NULL,
  updateTime DATETIME NOT NULL,
  status INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DROP TABLE IF EXISTS `book`;
CREATE TABLE `book`
(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  bookName VARCHAR(50) NOT NULL,
  userId INT NOT NULL,
  coverUrl VARCHAR(256) NOT NULL DEFAULT '',
  pdfUrl VARCHAR(256) NOT NULL DEFAULT '',
  downloadCount INT NOT NULL DEFAULT 0,
  score INT NOT NULL DEFAULT 0,
  createTime DATETIME NOT NULL,
  updateTime DATETIME NOT NULL,
  status INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8;