DROP TABLE IF EXISTS `user`;
CREATE TABLE `user`
(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  username VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  salt VARCHAR(50) NOT NULL,
  createTime DATETIME NOT NULL,
  updateTime DATETIME NOT NULL,
  status INT NOT NULL DEFAULT 0
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

